// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFwm-qpSbDZH5gGPMrR8EAY208s2zBkGg',
    appId: '1:1092257762850:web:7e08e7404324440dff447b',
    messagingSenderId: '1092257762850',
    projectId: 'quiz-na-yo-3d55d',
    authDomain: 'quiz-na-yo-3d55d.firebaseapp.com',
    storageBucket: 'quiz-na-yo-3d55d.firebasestorage.app',
    measurementId: 'G-2FSN3VNK91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8G0Z0n8AQ_CtSltAHLIEfG6nAKD2sjs8',
    appId: '1:1092257762850:android:ffa06ccf2faeaf33ff447b',
    messagingSenderId: '1092257762850',
    projectId: 'quiz-na-yo-3d55d',
    storageBucket: 'quiz-na-yo-3d55d.firebasestorage.app',
  );
}
